image: docker:latest
services:
- docker:dind

stages:
- build
- latest
- manual

variables:
  TEST_IMAGE: registry.gitlab.com/i105/admin-indygoapp:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: registry.gitlab.com/i105/admin-indygoapp:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com/i105/admin-indygoapp

build:
  stage: build
  script:
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE
  only:
    - master
    - tag

manual:
  stage: manual
  script:
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE
  when:
    manual

latest:
  stage: latest
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - master
    - tag
  when:
    manual
